config/routes.rb
Rails.application.routes.draw do
   resources :posts do 

   member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
  end 
end 
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

   get     'search'   =>      'users#index'

   get 'show' => 'posts#show'
 
  devise_for :users

  

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :message, presence: true
  validates :message, length: {maximum: 140, 
too_long: "A Post is only 140 max. Everybody knows that!"}

geocoded_by :address
 after_validation :geocode

acts_as_votable

 def score
  self.get_upvotes.size - self.get_downvotes.size
end


 def address
 	"#{destination}"
end
 def self.search(search)
  where("name LIKE ?", "%#{search}%") 
  where("content LIKE ?", "%#{search}%")
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :posts
  validates :username, presence: true, uniqueness: true

  serialize :following, Array
  
  
  def self.search(search)
  where("name LIKE ?", "%#{search}%") 
  where("content LIKE ?", "%#{search}%")
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following, :avatar,:longitude,:latitude) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following, :avatar,:longitude,:latitude) }

  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_filter :authenticate_user!, except: [:show_user]

  def feed
@images = ["2bikes.jpg","first.jpg","groupbike.jpg","tunnel.jpg"]
    @post = Post.new

    @followercount = 0
    User.all.each do |u|
      if u.following.include?(current_user.id)
        @followercount += 1
      end
    end

  	@following_posts = []
  
  	Post.all.each do |post|
  		if current_user.following.include?(post.user_id) || post.user_id == current_user.id
  			@following_posts.push(post)
  		end
  	end
  	if params[:search]
    @users = User.search(params[:search]).order("created_at DESC")
  else
    @users = User.all.order('created_at DESC')
  end
  end

   def show_user
    @user = User.find(params[:id])
  end

  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save

  	redirect_to :back
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to :back
  end

  def followers
    @user = User.find(params[:id])
    @users = []
    User.all.each do |u|
      if u.following.include?(@user.id)
        @users.push(u)
      end
    end
  end

  def following
    @user = User.find(params[:id])
    @users = []
    User.all.each do |u|
      if @user.following.include?(u.id)
        @users.push(u)
      end
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
before_filter :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

  end
   def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to root_path
  end
  def downvote
  @post = Post.find(params[:id])
  @post.downvote_by current_user
  redirect_to root_path
end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:message, :user_id,:destination,:latitude,:longitude,:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/epicenter/_currentuser_stats.html.erb
<div class="col-md-4">
	<div class="row userstats">
		<div class="col-md-2">
			
		</div>
		<div class="col-md-10">
			<h3><%= link_to current_user.name, show_user_path(id: current_user.id), class: "no-underline" %></h3>
			<p><%= link_to "@#{current_user.username}", show_user_path(id: current_user.id), class: "no-underline" %></p>
		</div>
	</div>
	<div class="row userstats">
		<div class="col-md-4">
			Meetups
		</div>
		<div class="col-md-4">
			Following
		</div>
		<div class="col-md-4">
			Followers
		</div>
	</div>
	<div class="row userstats">
		<div class="col-md-4">
			<%= link_to current_user.posts.count, show_user_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to current_user.following.count, following_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to @followercount, followers_path(id: current_user.id), class: "no-underline" %>
		</div>
	</div>
</div>

app/views/epicenter/_userstats.html.erb
<div class="col-md-3">
	<h3><%= link_to @user.name, show_user_path(id: @user.id) %></h3>
	<p><%= link_to "@#{@user.username}", show_user_path(id: @user.id) %></p>
	<p><%= @user.bio %></p>
	<p><i class="fa fa-map-marker"></i> <%= @user.location %></p>
	<p><i class="fa fa-calendar"></i> Joined <%= @user.created_at.strftime("%B %Y") %></p>
	<% if @user.id != current_user.id %>
		<p>
			<% if current_user.following.include?(@user.id) %>
				<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
			<% else %>
				<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
			<% end %>
		</p>
	<% end %>
</div>

app/views/epicenter/feed.html.erb
	

<div class"row">
	<div class"col-md-6">
		<div class"well">
	<div class="images">
	<% @images.each do |image| %>
	<p><%= image_tag image, alt: "Bike Pics", class: "img-responsive" %></p>

<% end %>
</div>


		<div class="new-post-area">


							<!-- Button for meetup posts -->
	<button id="showbutton" > Add Meetup
			<div id="postbutton">
			<div class="col-md-11 mtop-6">
			<%= render 'posts/form' %>
			
			</div>
	</button>	
				

			</div>


		<!--                      -->
		<div class="postscroll">
					<% @following_posts.take(5).each do |post| %>
		<div class="post-area">

					<p>
					<%= post.user.name %> <%= "@#{post.user.username}" %>

					&#8226; <%= time_ago_in_words(post.created_at) %>
					</p>
					<p> <%= post.message.html_safe %>
						<h5> Location: <%= post.destination%>	
 
					 </h5> 

     				<%= link_to 'Map Details:', post,class: "btn btn-primary"%></p>
     				<%= link_to "", like_post_path(post), class:"glyphicon glyphicon-thumbs-up like"%>
   					<%= link_to "" , dislike_post_path(post), class:"glyphicon glyphicon-thumbs-down unlike" %>
   				    <%= post.score %>
					<% end %>

<button class="button1">				
							<%= link_to "Total Meetups",show_user_path(id: current_user.id) %>
							<%=current_user.posts.count%>
</button>
	<%= javascript_tag do %>
   latitude = '<%= j @post.latitude.to_s %>';
   longitude = '<%= j @post.longitude.to_s %>';
   address = '<%= j @post.address %>';
 
<% end %>



		

app/views/epicenter/followers.html.erb
<div class="row">
	<%= render 'userstats' %>
	<div class="col-md-8 col-md-offset-1">
		<div class="row">
			<% @users.each do |user| %>
				<div class="col-md-4">
					<div class="well">
						<h3><%= link_to user.name, show_user_path(id: user.id) %></h3>
						<p><%= link_to "@#{user.username}", show_user_path(id: user.id) %></p>
						<p><%= user.bio %></p>
						<p><i class="fa fa-map-marker"></i> <%= user.location %></p>
						<p><i class="fa fa-calendar"></i> Joined <%= user.created_at.strftime("%B %Y") %></p>
						<% if user.id != current_user.id %>
							<p>
								<% if current_user.following.include?(user.id) %>
									<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
								<% else %>
									<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/following.html.erb
<div class="row">
	<%= render 'userstats' %>
	<div class="col-md-8 col-md-offset-1">
		<div class="row">
			<% @users.each do |user| %>
				<div class="col-md-4">
					<div class="well">
						<h3><%= link_to user.name, show_user_path(id: user.id) %></h3>
						<p><%= link_to "@#{user.username}", show_user_path(id: user.id) %></p>
						<p><%= user.bio %></p>
						<p><i class="fa fa-map-marker"></i> <%= user.location %></p>
						<p><i class="fa fa-calendar"></i> Joined <%= user.created_at.strftime("%B %Y") %></p>
						<% if user.id != current_user.id %>
							<p>
								<% if current_user.following.include?(user.id) %>
									<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
								<% else %>
									<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/now_following.html.erb
<p> You are now following: <%= @user.username %> </p>

app/views/epicenter/show_user.html.erb
<div class="showuser">
<h1> @<%= @user.name %>'s Profile &amp; Posts </h1>
<div class="userspecs">
	<%= image_tag @user.avatar.url, class: "profilepic" %>
<p> <strong> User Name: </strong></br> <%= @user.name %> </p>
<p> <strong> User Location: </strong> </br> <%= @user.location %> </p>
<p> <strong> User Bio: </strong> </br> <%= @user.bio %></p>
				

</div>
<% if user_signed_in? && @user.id != current_user.id %>

<p>

	<% if current_user.following.include?(@user.id) %>
	<%= link_to "Unfollow", unfollow_path(id: @user.id), class: "btn btn-danger" %>
<%else%>
	<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
<%end%>
</p>
<%end%>

<div class="row">
			<% @user.posts.take(5).each do |post| %>

	<div class="col-md-3">
	<%= link_to 'Meetup Details:', post,class: "btn btn-primary"%></p>

	
	<p> <%= post.message %> </p>
	<p> <strong>By: </strong> @<%= post.user.username %> </p>



</div>
<%end%>	
</div>


</div>

app/views/epicenter/unfollow.html.erb
<h1>Epicenter#unfollow</h1>
<p>Find me in app/views/epicenter/unfollow.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>MotoMeetUp</title>
  <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCHojN0s6LYhp7yrbfwCI4WDF9hyvouC78">
 </script>


  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
	<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fa fa-home"></i> Home
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to posts_path do %>
              <i class="fa fa-motorcycle"></i> All Posts

            <% end %>
           
          </li>
        </ul>
       
        <% if user_signed_in? %>

          <ul class="nav navbar-nav navbar-right">
              <h6> Welcome <%= current_user.username %>  ... Following:    <%= link_to current_user.following.count %> ... Followers:    <%= link_to current_user.following.count %> </h6>
               
            <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>


            <!-- form for user search -->
              <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
              <%= submit_tag "Search" %>
             
<% end %>

          </ul>

        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
		<%= yield %>
	</div>


      <footer>
    &copy; 2016 Kenan J. Bali
  </footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>

    <%= f.text_field :message,class: "form-control" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
  <%= f.label :destination %> <br>
  <%= f.text_field :destination,class: "form-control"%>
</div>
 <div class="field">

  <%= f.hidden_field :longitude,class: "form-control"%>
</div>
 <div class="field">

  <%= f.hidden_field :latitude,class: "form-control"%>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.message %></td>
        
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="showmessage">
<div id="destination-map">
</div>
<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.username %>
</p>
<p>
<strong> Destination </strong>
<%= @post.destination %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', root_path %>
</div>

	
	<%= javascript_tag do %>
   latitude = '<%= j @post.latitude.to_s %>';
   longitude = '<%= j @post.longitude.to_s %>';
   address = '<%= j @post.address %>';
 
<% end %>